<h1>
	Login Credentials for CCS
</h1>
<table class="table table-responsive table-hover table-striped">
	<tr>
		<thead>
			<tr class="text-primary bg-info">
				<th>Sr #</th>
				<th>Username</th>
				<th>User Type</th>
				<th>Email</th>
				<th>Password</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>dexdevs</td>
				<td>superadmin</td>
				<td>dexdevs007@gmail.com</td>
				<td>dexdevs321</td>
			</tr>
			<tr>
				<td>2</td>
				<td>kinza</td>
				<td>admin</td>
				<td>kinza.fatima.522@gmail.com</td>
				<td>kinza123</td>
			</tr>
			<tr>
				<td>3</td>
				<td>nadia</td>
				<td>Subscriber</td>
				<td>nadiagull285@gmail.com</td>
				<td>nadia123</td>
			</tr>
			<tr>
				<td>4</td>
				<td>anasshafqat</td>
				<td>Subscriber</td>
				<td>anasshafqat01@gmail.com</td>
				<td>anas123</td>
			</tr>
			<tr>
				<td>5</td>
				<td>faraz_reviewer</td>
				<td>reviewer</td>
				<td>admin@ranafaraz.com</td>
				<td>admin123</td>
			</tr>
			<tr>
				<td>6</td>
				<td>anas</td>
				<td>reviewer</td>
				<td>anas@dexdevs.com</td>
				<td>anas123</td>
			</tr>
		</tbody>
	</tr>
</table>